"""
Django settings for academic_portal project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    # 'unfold.contrib.filters',  # optional contrib module, disabled to avoid import error
    # 'unfold.contrib.forms',    # optional contrib module
    # 'unfold.contrib.import_export',  # optional contrib module
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'tinymce',
    'portfolio',
    # 'axes',
    'adminsortable2',
    'import_export',
    'compressor',
    'maintenance_mode',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'axes.middleware.AxesMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # 'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

ROOT_URLCONF = 'academic_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academic_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

COMPRESS_ENABLED = not DEBUG
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.rJSMinFilter',
]

# Maintenance Mode
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True
MAINTENANCE_MODE_STATE_BACKEND = 'maintenance_mode.backends.LocalFileBackend'


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

CRYPTOGRAPHY_KEY = os.environ.get('CRYPTOGRAPHY_KEY', 'default-django-crypto-key-replace-in-prod').encode('utf-8')


UNFOLD = {
    'SITE_TITLE': 'PROTOFOLIO // COMMAND NODE',
    'SITE_HEADER': 'SYSTEM CONTROL MATRIX',
    'DASHBOARD_CALLBACK': 'portfolio.utils.dashboard_callback',
    'THEME': 'dark',

    # ── Primary colour palette — violet/indigo (#8b5cf6 at 500) ─────────────────
    # All values are space-separated R G B (no # prefix) as required by Unfold.
    'COLORS': {
        'primary': {
            '50':  '245 243 255',
            '100': '237 233 254',
            '200': '221 214 254',
            '300': '196 181 253',
            '400': '167 139 250',
            '500': '139 92 246',   # #8b5cf6 — active links, badges, highlights
            '600': '124 58 237',
            '700': '109 40 217',
            '800': '91 33 182',
            '900': '76 29 149',
            '950': '46 16 101',
        },
    },

    # ── Explicit sidebar navigation tree ───────────────────────────────────────
    # Category titles are uppercase for the terminal aesthetic.
    # Icons are Material Symbols names (Unfold renders them automatically).
    'NAVIGATION': [
        {
            'title': _('SYSTEMS INFRASTRUCTURE'),
            'separator': True,
            'collapsible': False,
            'items': [
                {
                    'title': _('System Deployments'),
                    'icon': 'router',
                    'link': reverse_lazy('admin:portfolio_systemdeployment_changelist'),
                },
                {
                    'title': _('Live Projects'),
                    'icon': 'analytics',
                    'link': reverse_lazy('admin:portfolio_liveproject_changelist'),
                },
                {
                    'title': _('Lab Prototypes'),
                    'icon': 'biotech',
                    'link': reverse_lazy('admin:portfolio_labprototype_changelist'),
                },
                {
                    'title': _('Local Resources'),
                    'icon': 'folder_open',
                    'link': reverse_lazy('admin:portfolio_localresource_changelist'),
                },
            ],
        },

        # ── NEW: Knowledge Vault ─────────────────────────────────────────────
        {
            'title': _('KNOWLEDGE VAULT'),
            'separator': True,
            'collapsible': False,
            'items': [
                {
                    'title': _('Certificates'),
                    'icon': 'verified',
                    'link': lambda r: reverse_lazy('admin:portfolio_knowledgeasset_changelist').__str__() + '?asset_type=CERTIFICATE',
                },
                {
                    'title': _('Learning Modules'),
                    'icon': 'menu_book',
                    'link': lambda r: reverse_lazy('admin:portfolio_knowledgeasset_changelist').__str__() + '?asset_type=LEARNING_MODULE',
                },
            ],
        },
        # ────────────────────────────────────────────────────────────────────

        {
            'title': _('CONTENT PIPELINE'),
            'separator': True,
            'collapsible': False,
            'items': [
                {
                    'title': _('Publications'),
                    'icon': 'article',
                    'link': reverse_lazy('admin:portfolio_publication_changelist'),
                },
                {
                    'title': _('Tech Stack Metrics'),
                    'icon': 'layers',
                    'link': reverse_lazy('admin:portfolio_techstackmetric_changelist'),
                },
                {
                    'title': _('Open Source'),
                    'icon': 'code',
                    'link': reverse_lazy('admin:portfolio_opensourcecontribution_changelist'),
                },
                {
                    'title': _('Terminal Logs'),
                    'icon': 'terminal',
                    'link': reverse_lazy('admin:portfolio_terminallog_changelist'),
                },
                {
                    'title': _('Peer References'),
                    'icon': 'verified_user',
                    'link': reverse_lazy('admin:portfolio_peerreference_changelist'),
                },
                {
                    'title': _('Asset Attachments'),
                    'icon': 'attach_file',
                    'link': reverse_lazy('admin:portfolio_assetattachment_changelist'),
                },
            ],
        },

        {
            'title': _('IDENTITY CORE'),
            'separator': True,
            'collapsible': False,
            'items': [
                {
                    'title': _('Profile'),
                    'icon': 'person',
                    'link': reverse_lazy('admin:portfolio_profile_changelist'),
                },
            ],
        },

        {
            'title': _('USER MANAGEMENT'),
            'separator': True,
            'collapsible': True,
            'items': [
                {
                    'title': _('Users'),
                    'icon': 'manage_accounts',
                    'link': reverse_lazy('admin:auth_user_changelist'),
                },
                {
                    'title': _('Groups'),
                    'icon': 'group',
                    'link': reverse_lazy('admin:auth_group_changelist'),
                },
            ],
        },
    ],
}

# Google Drive Integration Settings
GOOGLE_DRIVE_FOLDER_ID = "1JoUaUR4j9KFPg_cDL0F0gn2lrTZcbC8W"
GOOGLE_DRIVE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials', 'google_drive_key.json')
GOOGLE_DRIVE_API_KEY = os.environ.get('GOOGLE_DRIVE_API_KEY', '')
