# Generated by Django 5.2.13 on 2026-05-01 12:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabi/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('bio', tinymce.models.HTMLField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('journal_conference_name', models.CharField(max_length=300)),
                ('year_of_publication', models.IntegerField()),
                ('abstract', tinymce.models.HTMLField()),
                ('doi_link', models.URLField(blank=True, null=True, verbose_name='DOI/Link')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('funding_agency', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=50)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
