# Generated by Django 4.2.30 on 2026-05-01 12:35

from django.db import migrations, models
import django_cryptography.fields
import portfolio.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=django_cryptography.fields.encrypt(tinymce.models.HTMLField()),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/', validators=[portfolio.validators.validate_is_pdf]),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=django_cryptography.fields.encrypt(tinymce.models.HTMLField()),
        ),
    ]
