# Generated by Django 4.2.30 on 2026-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_course_deleted_course_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='course',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='deleted_by_cascade',
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsannouncement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsannouncement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
