# Generated by Django 4.2.30 on 2026-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_course_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bibtex',
            field=models.TextField(blank=True, null=True, verbose_name='BibTeX Citation'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('Journal', 'Journal Article'), ('Conference', 'Conference Paper'), ('Book', 'Book/Chapter')], default='Journal', max_length=20),
        ),
    ]
