# Generated by Django 4.2.30 on 2026-05-03 16:37

from django.db import migrations, models
import django.db.models.deletion
import portfolio.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_publication_bibtex_publication_publication_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public Visibility'),
        ),
        migrations.AddField(
            model_name='newsannouncement',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public Visibility'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cv/', validators=[portfolio.validators.validate_is_pdf], verbose_name='Academic CV (PDF)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_about_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'About Me'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_academic_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'Academic Appointments'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'Administrative Appointments'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_boards_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'Organizations & Boards'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_education_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'Professional Education'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_honors_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'Honors & Awards'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public Visibility'),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public Visibility'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public Visibility'),
        ),
        migrations.CreateModel(
            name='ProfessionalEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Professional Education',
                'verbose_name_plural': 'Professional Education',
            },
        ),
        migrations.CreateModel(
            name='OrganizationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('org_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('committee_type', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_boards', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Organization & Board',
                'verbose_name_plural': 'Organizations & Boards',
            },
        ),
        migrations.CreateModel(
            name='HonorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('award_name', models.CharField(max_length=255)),
                ('granting_body', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors_awards', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Honor & Award',
                'verbose_name_plural': 'Honors & Awards',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('role', models.CharField(help_text='e.g., Head of Department', max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('responsibilities', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_appointments', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Administrative Appointment',
                'verbose_name_plural': 'Administrative Appointments',
            },
        ),
        migrations.CreateModel(
            name='AcademicAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('position', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_appointments', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Academic Appointment',
                'verbose_name_plural': 'Academic Appointments',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('bio', tinymce.models.HTMLField(verbose_name='Narrative Bio')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[portfolio.validators.validate_is_video], verbose_name='Introduction Video (MP4/MOV)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'About Me Section',
                'verbose_name_plural': 'About Me Sections',
            },
        ),
    ]
