# Generated by Django 4.2.30 on 2026-05-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_profile_bio_course_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='horizontal_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='media_position',
            field=models.CharField(choices=[('left', 'Media Left'), ('right', 'Media Right')], default='left', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='section_order',
            field=models.PositiveIntegerField(default=0, help_text='Drag and drop or set order for sections'),
        ),
    ]
