# Generated by Django 4.2.30 on 2026-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_horizontal_alignment_profile_media_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='section_order',
        ),
        migrations.AddField(
            model_name='profile',
            name='order_about',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_academic',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_admin',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_boards',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_education',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_honors',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
