# Generated by Django 4.2.30 on 2026-05-03 17:11

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_profile_section_order_profile_order_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaleducation',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_patents_visible',
            field=models.BooleanField(default=True, verbose_name="Show 'Patents'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_patents',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_area',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Research Area'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teaching_area',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Teaching Area'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Narrative Bio'),
        ),
        migrations.AlterField(
            model_name='academicappointment',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicappointment',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicappointment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativeappointment',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrativeappointment',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativeappointment',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='honoraward',
            name='award_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='honoraward',
            name='granting_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='honoraward',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='headline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='organizationboard',
            name='committee_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationboard',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationboard',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionaleducation',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionaleducation',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionaleducation',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='horizontal_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='media_position',
            field=models.CharField(blank=True, choices=[('left', 'Media Left'), ('right', 'Media Right')], default='left', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=django_cryptography.fields.encrypt(tinymce.models.HTMLField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_conference_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('Journal', 'Journal Article'), ('Conference', 'Conference Paper'), ('Book', 'Book/Chapter')], default='Journal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year_of_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=django_cryptography.fields.encrypt(tinymce.models.HTMLField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='project_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('patent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, help_text='Published/Granted', max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('link_or_file', models.FileField(blank=True, help_text='Upload PDF or CV will link to DOI if URL is pasted below', null=True, upload_to='patents/')),
                ('url', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Patent',
                'verbose_name_plural': 'Patents',
            },
        ),
    ]
