# Generated by Django 4.2.30 on 2026-05-18 07:32

from django.db import migrations, models
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_professionaleducation_year_profile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_downloads/', validators=[portfolio.validators.validate_is_pdf], verbose_name='Full Portfolio (PDF)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_json',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume Data (JSON)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
