# Generated by Django 4.2.30 on 2026-05-18 07:37

from django.db import migrations, models
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_portfolio_pdf_profile_resume_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('title', models.CharField(max_length=255)),
                ('system_status', models.CharField(default='Operational', max_length=50)),
                ('uptime_percentage', models.FloatField(default=99.9)),
                ('live_deployment_url', models.URLField(blank=True, null=True)),
                ('github_sync_url', models.URLField(blank=True, null=True)),
                ('active_api_requests', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('title', models.CharField(max_length=255)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='resources/', validators=[portfolio.validators.validate_is_pdf])),
                ('resource_type', models.CharField(default='PDF', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
