# Generated by Django 4.2.30 on 2026-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_liveproject_localresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveproject',
            options={'ordering': ['-last_synced']},
        ),
        migrations.RenameField(
            model_name='liveproject',
            old_name='last_updated',
            new_name='last_synced',
        ),
        migrations.AddField(
            model_name='liveproject',
            name='drive_folder_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localresource',
            name='web_view_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveproject',
            name='active_api_requests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='liveproject',
            name='system_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Maintenance'), ('OFFLINE', 'Offline')], default='OPERATIONAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='liveproject',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='liveproject',
            name='uptime_percentage',
            field=models.FloatField(blank=True, default=99.9, null=True),
        ),
        migrations.AlterField(
            model_name='localresource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
