# Generated by Django 4.2.30 on 2026-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_liveproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Visibility')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('telemetry_metric', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('system_architecture', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'System Deployment',
                'verbose_name_plural': 'System Deployments',
                'ordering': ['order'],
            },
        ),
    ]
