# Generated by Django 4.2.30 on 2026-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_systemdeployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime_environment', models.CharField(default='Python 3.11 // PyTorch', max_length=100)),
                ('notebook_or_file', models.FileField(blank=True, null=True, upload_to='lab_sandbox/')),
                ('mathematical_core', models.TextField(blank=True, help_text='Formulas, optimization loss details, or algorithm logic', null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSourceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pull_request_url', models.URLField(blank=True, null=True)),
                ('impact_summary', models.TextField(blank=True, help_text='What structural code did you optimize or refactor?', null=True)),
                ('lines_optimized', models.IntegerField(blank=True, default=0, null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_or_title', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_hash', models.CharField(blank=True, help_text='Optional secure validator hash', max_length=64, null=True)),
                ('statement', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TechStackMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('CORE_LANG', 'Languages & Runtimes'), ('AIML_FRAME', 'AI/ML & Data Engineering'), ('INFRA_CLOUD', 'Infrastructure & Databases')], default='CORE_LANG', max_length=50)),
                ('verified_use_cases', models.TextField(blank=True, help_text='E.g., Used in Sentinel V7 for river water mapping', null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_level', models.CharField(default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
