# Generated by Django 4.2.30 on 2026-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_labprototype_opensourcecontribution_peerreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprototype',
            name='auto_sync_assets',
            field=models.BooleanField(default=True, help_text='If enabled, background cron tasks will systematically parse this folder.'),
        ),
        migrations.AddField(
            model_name='labprototype',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='Target Google Drive Folder ID (e.g., 1JoUaUR4j9KFPg_cDL0F0gn2lrTZcbC8W)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeployment',
            name='auto_sync_assets',
            field=models.BooleanField(default=True, help_text='If enabled, background cron tasks will systematically parse this folder.'),
        ),
        migrations.AddField(
            model_name='systemdeployment',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text='Target Google Drive Folder ID (e.g., 1JoUaUR4j9KFPg_cDL0F0gn2lrTZcbC8W)', max_length=255, null=True),
        ),
    ]
