# Generated by Django 4.2.30 on 2026-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_labprototype_auto_sync_assets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Systems Identity Core', 'verbose_name_plural': 'Systems Identity Cores'},
        ),
        migrations.AddField(
            model_name='profile',
            name='core_mindset_philosophy',
            field=models.TextField(blank=True, help_text='Details your technical execution rules (e.g., performance tuning, heuristic optimization, security first).', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, default='Full Stack Developer & AI/ML Engineer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='immediate_system_goals',
            field=models.TextField(blank=True, help_text='Bullet-pointed or structural breakdown of current active milestones.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='manifesto_statement',
            field=models.TextField(blank=True, help_text='A high-end, single-sentence operational thesis framing your overall work.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_signature_initial',
            field=models.CharField(blank=True, default='A', max_length=10, null=True),
        ),
    ]
