# Generated by Django 4.2.30 on 2026-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstackmetric',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
