# Generated by Django 4.2.30 on 2026-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_techstackmetric_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstackmetric',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='techstackmetric',
            name='category',
            field=models.CharField(choices=[('WEB_EDGE', 'Web & Edge Infrastructure'), ('AI_CORE', 'Artificial Intelligence & Data'), ('QUANTUM', 'Quantum Engineering'), ('SECURITY', 'Systems Security & Vaults')], default='WEB_EDGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='techstackmetric',
            name='verified_use_cases',
            field=models.TextField(blank=True, help_text='Verified production use cases.', null=True),
        ),
    ]
