# Generated by Django 4.2.30 on 2026-05-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_techstackmetric_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_folder_id', models.CharField(blank=True, help_text='Target Google Drive Folder ID (e.g., 1JoUaUR4j9KFPg_cDL0F0gn2lrTZcbC8W)', max_length=255, null=True)),
                ('auto_sync_assets', models.BooleanField(default=True, help_text='If enabled, background cron tasks will systematically parse this folder.')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('core_concept_approaches', models.TextField(blank=True, help_text='Detailed approach matrices (Micro, Macro, Hybrid).', null=True)),
                ('key_parameters', models.TextField(blank=True, help_text='Sensor benchmarks and computer vision monitoring vectors.', null=True)),
                ('ml_architectures', models.TextField(blank=True, help_text='Specific model structures (YOLOv8, Isolation Forest, LSTMs).', null=True)),
                ('system_architecture_layers', models.TextField(blank=True, help_text='End-to-end operational pipeline stack loops.', null=True)),
                ('implementation_mvp_steps', models.TextField(blank=True, help_text='Phased developmental execution directives.', null=True)),
                ('advanced_features', models.TextField(blank=True, help_text='Advanced technical enhancements (Digital Twins, Source Tracing).', null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'R&D Architecture Blueprint',
                'verbose_name_plural': 'R&D Architecture Blueprints',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
