# Generated by Django 4.2.30 on 2026-05-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0020_learningproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='E.g., Production Blueprint PDF, JSON Configuration Schema', max_length=150)),
                ('resource_type', models.CharField(choices=[('LOCAL', 'Local Disk Storage'), ('DRIVE', 'Google Drive Asset Link')], default='LOCAL', max_length=10)),
                ('local_file', models.FileField(blank=True, help_text='Upload directly to your server storage.', null=True, upload_to='section_assets/')),
                ('drive_direct_url', models.URLField(blank=True, help_text='Drop the unrestricted sharing or download link from Google Drive.', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'System Asset Attachment',
                'verbose_name_plural': 'System Asset Attachments',
            },
        ),
    ]
