# Generated by Django 4.2.30 on 2026-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_assetattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_folder_id', models.CharField(blank=True, help_text='Target Google Drive Folder ID (e.g., 1JoUaUR4j9KFPg_cDL0F0gn2lrTZcbC8W)', max_length=255, null=True)),
                ('auto_sync_assets', models.BooleanField(default=True, help_text='If enabled, background cron tasks will systematically parse this folder.')),
                ('title', models.CharField(blank=True, help_text="E.g., Infosys 'Carbon Smart' Certification", max_length=255, null=True)),
                ('issuing_authority', models.CharField(blank=True, help_text='E.g., Dr. A.P.J. Abdul Kalam AI Lab', max_length=255, null=True)),
                ('classification', models.CharField(choices=[('CERTIFICATION', 'Professional Certification'), ('AWARD', 'System Distinction / Award'), ('MILESTONE', 'Infrastructure Milestone')], default='CERTIFICATION', max_length=20)),
                ('date_secured', models.DateField(blank=True, null=True)),
                ('local_credential_file', models.FileField(blank=True, help_text='Upload certificate directly (PDF, JPG, PNG).', null=True, upload_to='credentials_vault/')),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Validation Milestone',
                'verbose_name_plural': 'System Validation Milestones',
                'ordering': ['order', '-date_secured'],
            },
        ),
    ]
