# Generated by Django 4.2.30 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_validationmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Human-readable asset name (e.g. 'AWS Solutions Architect – Associate').", max_length=255)),
                ('asset_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('LEARNING_MODULE', 'Learning Module')], db_index=True, default='CERTIFICATE', max_length=20)),
                ('storage_provider', models.CharField(choices=[('LOCAL_DISK', 'Local Disk'), ('GOOGLE_DRIVE', 'Google Drive')], default='LOCAL_DISK', help_text='Where the underlying file lives.', max_length=15)),
                ('uri', models.CharField(blank=True, help_text='LOCAL_DISK → absolute server path (must be inside MEDIA_ROOT). GOOGLE_DRIVE → Drive File ID (e.g. 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms).', max_length=1024, null=True)),
                ('local_file', models.FileField(blank=True, help_text='Upload the file directly. Takes precedence over URI for LOCAL_DISK assets.', null=True, upload_to='knowledge_vault/')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON payload. Examples: {"issuer": "Coursera", "issued_date": "2024-03", "tags": ["Python", "ML"]} or {"platform": "Udemy", "chapters": 42, "hours": 28.5}.')),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Knowledge Asset',
                'verbose_name_plural': 'Knowledge Assets',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['asset_type', 'is_public'], name='portfolio_k_asset_t_bdd1ea_idx')],
            },
        ),
    ]
