# Generated by Django 4.2.30 on 2026-05-21 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_add_knowledge_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideVentureAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SIDE_VENTURE', 'Side Venture'), ('UNPUBLISHED_CONTENT', 'Unpublished Content')], default='SIDE_VENTURE', max_length=50)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('BINARY', 'Compiled Binary'), ('DATASET', 'Dataset / JSON / CSV'), ('IMAGE', 'Image Asset'), ('RAW_CODE', 'Raw Source Code')], default='PDF', max_length=20)),
                ('storage_provider', models.CharField(choices=[('LOCAL_DISK', 'Local Disk'), ('GOOGLE_DRIVE', 'Google Drive')], default='LOCAL_DISK', max_length=20)),
                ('uri', models.CharField(blank=True, help_text='Generated automatically upon upload', max_length=1024, null=True)),
                ('upload', models.FileField(blank=True, help_text='Upload your asset here.', null=True, upload_to='ventures/')),
                ('is_public', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Side Venture & Unpublished Content',
                'verbose_name_plural': 'Side Ventures & Unpublished Content',
                'ordering': ['order', '-timestamp'],
            },
        ),
    ]
